#ifndef PHOEBUS_UTILS_PREPROCESSOR_UTILS_HPP_
#define PHOEBUS_UTILS_PREPROCESSOR_UTILS_HPP_

#define TOKEN2STRING_IMPL(x) #x
#define TOKEN2STRING(x) TOKEN2STRING_IMPL(x)

#endif // PHOEBUS_UTILS_PREPROCESSOR_UTILS_HPP_
