set(PHOEBUS_RADIATION_METHOD "MonteCarlo" CACHE STRING "Numerical method for radiation transport")

set(PHOEBUS_RADIATION_METHODS
    "OpticallyThinCooling"
    "Diffusion"
    "M1"
    "MonteCarlo"
    "MOCMC"
   )

if(PHOEBUS_RADIATION_METHOD IN_LIST PHOEBUS_RADIATION_METHODS)
  set(RADIATION_METHOD "${PHOEBUS_RADIATION_METHOD}")
else()
  message(FATAL_ERROR "Unknown PHOEBUS_RADIATION_METHOD!")
endif()

set(PHOEBUS_RADIATION_BOUND_IX1 "outflow" CACHE STRING "Lower X1 radiation boundary condition")
set(PHOEBUS_RADIATION_BOUND_OX1 "outflow" CACHE STRING "Upper X1 radiation boundary condition")
set(PHOEBUS_RADIATION_BOUND_IX2 "outflow" CACHE STRING "Lower X2 radiation boundary condition")
set(PHOEBUS_RADIATION_BOUND_OX2 "outflow" CACHE STRING "Upper X2 radiation boundary condition")
set(PHOEBUS_RADIATION_BOUND_IX3 "outflow" CACHE STRING "Lower X3 radiation boundary condition")
set(PHOEBUS_RADIATION_BOUND_OX3 "outflow" CACHE STRING "Upper X3 radiation boundary condition")

set(PHOEBUS_RADIATION_BOUNDS
    "periodic"
    "outflow"
    "reflecting"
    "thermal"
   )

if(PHOEBUS_RADIATION_BOUND_IX1 IN_LIST PHOEBUS_RADIATION_BOUNDS)
  set(RADIATION_BOUND_IX1 "${PHOEBUS_RADIATION_BOUND_IX1}")
else()
  message(FATAL_ERROR "Unknown PHOEBUS_RADIATION_BOUND_IX1!")
endif()
if(PHOEBUS_RADIATION_BOUND_OX1 IN_LIST PHOEBUS_RADIATION_BOUNDS)
  set(RADIATION_BOUND_OX1 "${PHOEBUS_RADIATION_BOUND_OX1}")
else()
  message(FATAL_ERROR "Unknown PHOEBUS_RADIATION_BOUND_OX1!")
endif()
if(PHOEBUS_RADIATION_BOUND_IX2 IN_LIST PHOEBUS_RADIATION_BOUNDS)
  set(RADIATION_BOUND_IX2 "${PHOEBUS_RADIATION_BOUND_IX2}")
else()
  message(FATAL_ERROR "Unknown PHOEBUS_RADIATION_BOUND_IX2!")
endif()
if(PHOEBUS_RADIATION_BOUND_OX2 IN_LIST PHOEBUS_RADIATION_BOUNDS)
  set(RADIATION_BOUND_OX2 "${PHOEBUS_RADIATION_BOUND_OX2}")
else()
  message(FATAL_ERROR "Unknown PHOEBUS_RADIATION_BOUND_OX2!")
endif()
if(PHOEBUS_RADIATION_BOUND_IX3 IN_LIST PHOEBUS_RADIATION_BOUNDS)
  set(RADIATION_BOUND_IX3 "${PHOEBUS_RADIATION_BOUND_IX3}")
else()
  message(FATAL_ERROR "Unknown PHOEBUS_RADIATION_BOUND_IX3!")
endif()
if(PHOEBUS_RADIATION_BOUND_OX3 IN_LIST PHOEBUS_RADIATION_BOUNDS)
  set(RADIATION_BOUND_OX3 "${PHOEBUS_RADIATION_BOUND_OX3}")
else()
  message(FATAL_ERROR "Unknown PHOEBUS_RADIATION_BOUND_OX3!")
endif()
